version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    container_name: app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123ba
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW-SQL: false

  db:
    image: 'postgres:15'
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123ba
    ports:
      - "5432:5432"
